# مرحله 1: ساخت (Build)
FROM node:18-alpine AS builder

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

# مرحله 2: اجرای برنامه
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/.output .output
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
