FROM node:18-alpine AS builder

WORKDIR /app

COPY . /app

RUN npm install
RUN npm run build


FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/.output .output
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

CMD ["node", ".output/server/index.mjs"]